---
title: "R Notebook"
output: html_notebook
---


```{r setup}


library(tidyverse)
library(scales)
library(forcats)
library(gridExtra)
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
comment = "#>",
collapse = TRUE,
cache = TRUE,
out.width = "70%",
fig.align = 'center',
fig.width = 6,
fig.asp = 0.618,
# 1 / phi
fig.show = "hold",
dev = c("pdf", "png")
)

lappend <- function(lst, obj) {
lst[[length(lst) + 1]] <- obj
return(lst)
}

fun_name = "figure4"
output_dir = "./files"
dir.create(output_dir, showWarnings = FALSE)

options(dplyr.print_min = 6, dplyr.print_max = 6)

```


```{r figure_data}
load("../../R/objects/iMM904._load_.RData")
load("../../R/objects/exp_metadata._clean_.RData")
load("../../R/objects/orf2name._clean_.RData")
load("../../R/objects/metabolite2iMM904._load_.RData")
load("../../R/objects/gene.annotations._load_.RData")


load("../../R/objects/all_final_models.models_summary2.RData")
load("../../R/objects/file.list.models_summary2.RData")
```


#Figure B
```{r R2_barplot}


metabolites.models.long <- all_final_models %>% 
  filter(isImputed == 0, metabolite != "Glu") %>%
  dplyr::select(model, RMSE, Rsquared, normalization, dataset, metabolite, degree, preprocessing) %>% 
  distinct() %>%
  group_by(metabolite, normalization, degree, preprocessing) %>%
  filter(RMSE == min(RMSE,na.rm = T)) %>%
  group_by(metabolite, degree) %>%
  filter(Rsquared == max(Rsquared,na.rm = T))

length(unique(all_final_models$model))

metabolite.order <- read.delim("../../data/2015-10-16/metabolites.txt")
metabolite.order = metabolite.order[with(metabolite.order,order(desc(method),pathway,Order, met_name)),]


toPlot <- metabolites.models.long %>% filter(metabolite %in% metabolite.order$metabolite)


toPlot <- toPlot %>% mutate(met_name = metabolite.order$met_name[match(metabolite, metabolite.order$metabolite)],
                            met_name = fct_relevel(met_name, levels=as.character(metabolite.order$met_name)),
                            pathway = metabolite.order$pathway[match(metabolite, metabolite.order$metabolite)],
                            pathway = fct_relevel(pathway,levels = unique(as.character(metabolite.order$pathway))))

tests.pvals <- toPlot %>% 
  group_by(degree) %>% 
  summarise(p.value1 = wilcox.test(toPlot$Rsquared[toPlot$degree == 1], Rsquared)$p.value,
            p.value3 = wilcox.test(toPlot$Rsquared[toPlot$degree == 3], Rsquared)$p.value) %>% 
  as.data.frame() %>% 
  gather(variable, value, -degree) %>% 
  filter(value != 1) %>%
  group_by(degree, variable) %>%
  mutate(Rsquared = jitter(0.7,0.2))


toPlot %>%
  ggplot(aes(x=degree, y = Rsquared, fill = degree)) +
    stat_boxplot(geom ='errorbar', width = 0.5) +
    geom_boxplot() +
    ylab(expression(paste("Cross-validated ", R^2, sep=""))) +
    xlab("Network distance") +
    geom_text(data=tests.pvals, aes(label=format(value, scientific=T))) +
    theme_bw() +
    theme(legend.position="none",
          panel.grid = element_blank())

```

```{r distance}
toPlot.points <- toPlot %>% 
  group_by(metabolite) %>%
  filter(degree == 1) %>%
  filter(Rsquared == max(Rsquared,na.rm = T))

toPlot <- toPlot %>% 
  group_by(metabolite) %>%
  filter(Rsquared == max(Rsquared,na.rm = T))
toPlot %>%
  ggplot(aes(x = met_name, y = Rsquared, fill=degree)) +
    geom_bar(position="dodge", stat = "identity") +
    geom_point(data = toPlot.points, aes(x = met_name, y = Rsquared)) +
    ylab(expression(paste("Cross-validated ", R^2, sep=""))) +
    xlab("") +
    scale_y_continuous(breaks = seq(0, 1, 0.2), labels = as.character(seq(0, 1, 0.2)), limits = c(0,0.8)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = c(0.2, 0.7))
  
```

```{}


```


